groovy
plugins {
    id 'net.neoforged.moddev' version '1.0.1'
}

version = '1.21.1-1.0.0'
group = 'chumbanotz.mutantbeasts'

base {
    archivesName = 'mutantbeasts_endersoul'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = '21.1.65' // Актуальная стабильная версия NeoForge для 1.21.1

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        mutantbeasts {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
}
